#!/usr/bin/env python

import sys
from json import dumps
from getpass import getuser
from socket import gethostname
from urllib import urlencode, urlopen

user = getuser()
host = gethostname()
message = sys.stdin.read()

payload = {"user": user, "host": host, "message": message}
kwargs = {"channel": sys.argv[1], "payload": dumps(payload)}
data = urlencode(kwargs)

url = "http://arrow.shortcircuit.net.au/api/message"
response = urlopen(url, data)
print response.read()
